import {
  PrismaClient,
  Priority,
  LeadStage,
  LeadStatus,
  LeadSource,
  CallType,
  SimProvider,
} from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import { Pool } from 'pg';
import * as dotenv from 'dotenv';
import { join } from 'path';
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Load .env from apps/api directory
dotenv.config({ path: join(__dirname, '../.env') });

process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: {
    rejectUnauthorized: false, // Match PrismaService config
  },
});
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

// Helper function to map string values to enums
function mapPriority(val: string): Priority {
  const map: Record<string, Priority> = {
    High: 'HIGH',
    Medium: 'MEDIUM',
    Low: 'LOW',
  };
  return map[val] || 'MEDIUM';
}

function mapStage(val: string): LeadStage {
  const map: Record<string, LeadStage> = {
    'Call Done': 'CALL_DONE',
    'Followup Done': 'FOLLOWUP_DONE',
    'Demo Booked': 'DEMO_BOOKED',
    Negotiation: 'NEGOTIATION',
    'Future Connect': 'FUTURE_CONNECT',
  };
  return map[val] || 'CALL_DONE';
}

function mapStatus(val: string): LeadStatus {
  const map: Record<string, LeadStatus> = {
    New: 'NEW',
    Connected: 'CONNECTED',
    'Demo Done': 'DEMO_DONE',
    'Closed Won': 'CLOSED_WON',
    Lost: 'LOST',
    'Follow-up': 'FOLLOW_UP',
    'Demo Scheduled': 'FOLLOW_UP', // Map to closest
  };
  return map[val] || 'NEW';
}

function mapSource(val: string): LeadSource {
  const map: Record<string, LeadSource> = {
    Website: 'WEBSITE',
    Referral: 'REFERRAL',
    'Email Campaign': 'EMAIL_CAMPAIGN',
    'Social Media': 'SOCIAL_MEDIA',
  };
  return map[val] || 'WEBSITE';
}

function mapCallType(val: string): CallType {
  const map: Record<string, CallType> = {
    incoming: 'INCOMING',
    outgoing: 'OUTGOING',
    missed: 'MISSED',
    unanswered: 'UNANSWERED',
  };
  return map[val] || 'INCOMING';
}

function mapSimProvider(val: string): SimProvider {
  const map: Record<string, SimProvider> = {
    Vi: 'VI',
    Jio: 'JIO',
    Airtel: 'AIRTEL',
    BSNL: 'BSNL',
  };
  return map[val] || 'OTHER';
}

// Lead seed data (first 50 leads from the provided data)
const leadsData = [
  // Lead 1
  {
    leadName: 'Rahul Sharma',
    institution: 'Delhi Public School',
    phoneNumber: '9876543210',
    city: 'Delhi',
    priority: 'High',
    stage: 'Call Done',
    source: 'Website',
    owner: 'Ananya Sharma',
    status: 'New',
    createdAt: '2025-01-15T10:00:00Z',
  },
  // Lead 2
  {
    leadName: 'Anita Rao',
    institution: 'Green Valley School',
    phoneNumber: '9998887776',
    city: 'Bangalore',
    priority: 'Medium',
    stage: 'Followup Done',
    source: 'Referral',
    owner: 'Vikram Singh',
    status: 'Connected',
    createdAt: '2025-02-10T11:30:00Z',
  },
  // Lead 3
  {
    leadName: 'Sumit Patel',
    institution: 'Modern School',
    phoneNumber: '9345678123',
    city: 'Mumbai',
    priority: 'Low',
    stage: 'Demo Booked',
    source: 'Email Campaign',
    owner: 'Priya Patel',
    status: 'Demo Done',
    createdAt: '2025-03-05T09:15:00Z',
  },
  // Lead 4
  {
    leadName: 'Sonal Gupta',
    institution: 'City International',
    phoneNumber: '9812345678',
    city: 'Hyderabad',
    priority: 'High',
    stage: 'Negotiation',
    source: 'Referral',
    owner: 'Rahul Mehta',
    status: 'Closed Won',
    createdAt: '2025-01-20T14:45:00Z',
  },
  // Lead 5
  {
    leadName: 'Rakesh Kumar',
    institution: 'Sunshine Academy',
    phoneNumber: '9801223344',
    city: 'Kolkata',
    priority: 'Medium',
    stage: 'Demo Booked',
    source: 'Website',
    owner: 'Sneha Kapoor',
    status: 'Lost',
    createdAt: '2025-04-12T16:20:00Z',
  },
  // Lead 6
  {
    leadName: 'Priya Menon',
    institution: 'Oakridge School',
    phoneNumber: '9765432109',
    city: 'Chennai',
    priority: 'Low',
    stage: 'Future Connect',
    source: 'Social Media',
    owner: 'Karan Malhotra',
    status: 'Follow-up',
    createdAt: '2025-05-18T10:30:00Z',
  },
  // Lead 7
  {
    leadName: 'Amit Sharma',
    institution: 'Little Angels',
    phoneNumber: '9870123456',
    city: 'Pune',
    priority: 'Medium',
    stage: 'Negotiation',
    source: 'Website',
    owner: 'Deepika Iyer',
    status: 'Closed Won',
    createdAt: '2025-02-25T13:00:00Z',
  },
  // Lead 8
  {
    leadName: 'Lakshmi Nair',
    institution: 'Lotus Valley',
    phoneNumber: '9812678901',
    city: 'Delhi',
    priority: 'High',
    stage: 'Followup Done',
    source: 'Referral',
    owner: 'Ananya Sharma',
    status: 'New',
    createdAt: '2025-06-08T09:45:00Z',
  },
  // Lead 9
  {
    leadName: 'Ravi Teja',
    institution: 'St Xavier School',
    phoneNumber: '9876712345',
    city: 'Hyderabad',
    priority: 'Low',
    stage: 'Call Done',
    source: 'Website',
    owner: 'Vikram Singh',
    status: 'Connected',
    createdAt: '2025-07-14T11:20:00Z',
  },
  // Lead 10
  {
    leadName: 'Simran Kaur',
    institution: 'Blue Bells Academy',
    phoneNumber: '9813322110',
    city: 'Chandigarh',
    priority: 'Medium',
    stage: 'Demo Booked',
    source: 'Email Campaign',
    owner: 'Priya Patel',
    status: 'Demo Done',
    createdAt: '2025-03-30T15:10:00Z',
  },
  // Lead 11
  {
    leadName: 'Akash Mehta',
    institution: 'Global Public School',
    phoneNumber: '9922334455',
    city: 'Ahmedabad',
    priority: 'High',
    stage: 'Call Done',
    source: 'Social Media',
    owner: 'Rahul Mehta',
    status: 'Follow-up',
    createdAt: '2025-08-22T10:50:00Z',
  },
  // Lead 12
  {
    leadName: 'Surbhi Jain',
    institution: 'Heritage School',
    phoneNumber: '9888776655',
    city: 'Gurgaon',
    priority: 'High',
    stage: 'Negotiation',
    source: 'Social Media',
    owner: 'Sneha Kapoor',
    status: 'Closed Won',
    createdAt: '2025-01-05T12:00:00Z',
  },
  // Lead 13
  {
    leadName: 'Manoj Kumar',
    institution: 'Springfields High',
    phoneNumber: '9800112233',
    city: 'Dehradun',
    priority: 'Medium',
    stage: 'Demo Booked',
    source: 'Referral',
    owner: 'Karan Malhotra',
    status: 'Demo Done',
    createdAt: '2025-09-10T14:30:00Z',
  },
  // Lead 14
  {
    leadName: 'Divya Singh',
    institution: 'National Public School',
    phoneNumber: '9811456789',
    city: 'Bangalore',
    priority: 'High',
    stage: 'Call Done',
    source: 'Website',
    owner: 'Deepika Iyer',
    status: 'Follow-up',
    createdAt: '2025-04-05T16:00:00Z',
  },
  // Lead 15
  {
    leadName: 'Gaurav Mishra',
    institution: 'Hill Fort Academy',
    phoneNumber: '9912233445',
    city: 'Jaipur',
    priority: 'Low',
    stage: 'Future Connect',
    source: 'Social Media',
    owner: 'Ananya Sharma',
    status: 'Connected',
    createdAt: '2025-10-15T09:30:00Z',
  },
  // Lead 16
  {
    leadName: 'Meena Agarwal',
    institution: 'Sunrise Convent',
    phoneNumber: '9833446655',
    city: 'Bhopal',
    priority: 'High',
    stage: 'Negotiation',
    source: 'Referral',
    owner: 'Vikram Singh',
    status: 'Closed Won',
    createdAt: '2025-02-18T11:45:00Z',
  },
  // Lead 17
  {
    leadName: 'Vikas Pandey',
    institution: 'Cambridge School',
    phoneNumber: '9822233446',
    city: 'Lucknow',
    priority: 'Medium',
    stage: 'Followup Done',
    source: 'Email Campaign',
    owner: 'Priya Patel',
    status: 'Follow-up',
    createdAt: '2025-06-25T13:20:00Z',
  },
  // Lead 18
  {
    leadName: 'Sapna Joshi',
    institution: "St John's",
    phoneNumber: '9877665544',
    city: 'Nagpur',
    priority: 'Low',
    stage: 'Call Done',
    source: 'Website',
    owner: 'Rahul Mehta',
    status: 'Follow-up',
    createdAt: '2025-11-05T10:15:00Z',
  },
  // Lead 19
  {
    leadName: 'Farhan Akhtar',
    institution: 'Riverdale School',
    phoneNumber: '9844556677',
    city: 'Surat',
    priority: 'Medium',
    stage: 'Demo Booked',
    source: 'Referral',
    owner: 'Sneha Kapoor',
    status: 'Demo Done',
    createdAt: '2025-03-12T15:30:00Z',
  },
  // Lead 20
  {
    leadName: 'Shruti Desai',
    institution: 'Pearl Academy',
    phoneNumber: '9911223344',
    city: 'Ahmedabad',
    priority: 'High',
    stage: 'Followup Done',
    source: 'Social Media',
    owner: 'Karan Malhotra',
    status: 'FOLLOW_UP',
    createdAt: '2025-07-20T09:50:00Z',
  },
  // Lead 21
  {
    leadName: 'Pooja Reddy',
    institution: 'Gems School',
    phoneNumber: '9877662211',
    city: 'Hyderabad',
    priority: 'Low',
    stage: 'Future Connect',
    source: 'Referral',
    owner: 'Deepika Iyer',
    status: 'Connected',
    createdAt: '2025-12-01T11:10:00Z',
  },
  // Lead 22
  {
    leadName: 'Yashwanth Rao',
    institution: 'Presidium',
    phoneNumber: '9818764532',
    city: 'Delhi',
    priority: 'High',
    stage: 'Negotiation',
    source: 'Website',
    owner: 'Ananya Sharma',
    status: 'Closed Won',
    createdAt: '2025-01-28T14:00:00Z',
  },
  // Lead 23
  {
    leadName: 'Arjun Kapoor',
    institution: 'Ryan International',
    phoneNumber: '9876541122',
    city: 'Noida',
    priority: 'High',
    stage: 'Demo Booked',
    source: 'Referral',
    owner: 'Ananya Sharma',
    status: 'Demo Done',
    createdAt: '2025-05-15T16:30:00Z',
  },
  // Lead 24
  {
    leadName: 'Neha Bansal',
    institution: 'Oxford Academy',
    phoneNumber: '9988776655',
    city: 'Gurgaon',
    priority: 'Medium',
    stage: 'Call Done',
    source: 'Website',
    owner: 'Vikram Singh',
    status: 'Follow-up',
    createdAt: '2025-08-10T10:45:00Z',
  },
  // Lead 25
  {
    leadName: 'Rohit Verma',
    institution: 'DAV School',
    phoneNumber: '9912345678',
    city: 'Allahabad',
    priority: 'High',
    stage: 'Negotiation',
    source: 'Social Media',
    owner: 'Priya Patel',
    status: 'Closed Won',
    createdAt: '2025-02-05T13:15:00Z',
  },
  // Lead 26
  {
    leadName: 'Kavita Reddy',
    institution: 'Bhavan Vidyalaya',
    phoneNumber: '9823456789',
    city: 'Hyderabad',
    priority: 'Low',
    stage: 'Call Done',
    source: 'Email Campaign',
    owner: 'Rahul Mehta',
    status: 'Follow-up',
    createdAt: '2025-09-22T09:40:00Z',
  },
  // Lead 27
  {
    leadName: 'Suresh Nair',
    institution: 'Kendriya Vidyalaya',
    phoneNumber: '9734567890',
    city: 'Chennai',
    priority: 'Medium',
    stage: 'Followup Done',
    source: 'Referral',
    owner: 'Sneha Kapoor',
    status: 'FOLLOW_UP',
    createdAt: '2025-11-18T11:55:00Z',
  },
  // Lead 28
  {
    leadName: 'Manisha Yadav',
    institution: 'Amity School',
    phoneNumber: '9645678901',
    city: 'Noida',
    priority: 'High',
    stage: 'Followup Done',
    source: 'Website',
    owner: 'Karan Malhotra',
    status: 'FOLLOW_UP',
    createdAt: '2025-04-28T14:10:00Z',
  },
  // Lead 29
  {
    leadName: 'Ajay Thakur',
    institution: 'Army Public School',
    phoneNumber: '9556789012',
    city: 'Pune',
    priority: 'Medium',
    stage: 'Demo Booked',
    source: 'Referral',
    owner: 'Deepika Iyer',
    status: 'Demo Done',
    createdAt: '2025-06-15T16:45:00Z',
  },
  // Lead 30
  {
    leadName: 'Sanjay Mehta',
    institution: 'Vidya Niketan',
    phoneNumber: '9467890123',
    city: 'Delhi',
    priority: 'Low',
    stage: 'Future Connect',
    source: 'Social Media',
    owner: 'Ananya Sharma',
    status: 'Connected',
    createdAt: '2025-10-30T10:00:00Z',
  },
  // Lead 31
  {
    leadName: 'Ritu Saxena',
    institution: 'Mount Carmel',
    phoneNumber: '9378901234',
    city: 'Bangalore',
    priority: 'High',
    stage: 'Demo Booked',
    source: 'Website',
    owner: 'Vikram Singh',
    status: 'Demo Done',
    createdAt: '2025-01-10T12:30:00Z',
  },
  // Lead 32
  {
    leadName: 'Prakash Gupta',
    institution: 'St Marys Convent',
    phoneNumber: '9289012345',
    city: 'Mumbai',
    priority: 'Medium',
    stage: 'Call Done',
    source: 'Email Campaign',
    owner: 'Priya Patel',
    status: 'Follow-up',
    createdAt: '2025-07-05T09:15:00Z',
  },
  // Lead 33
  {
    leadName: 'Sunita Sharma',
    institution: 'Holy Cross',
    phoneNumber: '9190123456',
    city: 'Kolkata',
    priority: 'High',
    stage: 'Negotiation',
    source: 'Referral',
    owner: 'Rahul Mehta',
    status: 'Closed Won',
    createdAt: '2025-03-22T14:40:00Z',
  },
  // Lead 34
  {
    leadName: 'Arun Pillai',
    institution: 'Sacred Heart',
    phoneNumber: '9801234567',
    city: 'Kochi',
    priority: 'Low',
    stage: 'Followup Done',
    source: 'Social Media',
    owner: 'Sneha Kapoor',
    status: 'Lost',
    createdAt: '2025-08-18T11:00:00Z',
  },
  // Lead 35
  {
    leadName: 'Geeta Krishnan',
    institution: 'Bishop Cotton',
    phoneNumber: '9712345678',
    city: 'Bangalore',
    priority: 'Medium',
    stage: 'Negotiation',
    source: 'Website',
    owner: 'Karan Malhotra',
    status: 'Closed Won',
    createdAt: '2025-02-12T13:45:00Z',
  },
  // Lead 36
  {
    leadName: 'Vinay Kumar',
    institution: 'La Martiniere',
    phoneNumber: '9623456789',
    city: 'Lucknow',
    priority: 'High',
    stage: 'Demo Booked',
    source: 'Referral',
    owner: 'Deepika Iyer',
    status: 'Lost',
    createdAt: '2025-05-25T15:20:00Z',
  },
  // Lead 37
  {
    leadName: 'Rekha Iyer',
    institution: 'Chinmaya Vidyalaya',
    phoneNumber: '9534567890',
    city: 'Chennai',
    priority: 'Low',
    stage: 'Call Done',
    source: 'Email Campaign',
    owner: 'Ananya Sharma',
    status: 'Follow-up',
    createdAt: '2025-09-08T10:30:00Z',
  },
  // Lead 38
  {
    leadName: 'Mohan Das',
    institution: 'Sardar Patel School',
    phoneNumber: '9445678901',
    city: 'Ahmedabad',
    priority: 'Medium',
    stage: 'Followup Done',
    source: 'Social Media',
    owner: 'Vikram Singh',
    status: 'FOLLOW_UP',
    createdAt: '2025-11-28T12:00:00Z',
  },
  // Lead 39
  {
    leadName: 'Nandini Shah',
    institution: 'Shiv Nadar School',
    phoneNumber: '9356789012',
    city: 'Noida',
    priority: 'High',
    stage: 'Demo Booked',
    source: 'Website',
    owner: 'Priya Patel',
    status: 'Demo Done',
    createdAt: '2025-04-10T14:25:00Z',
  },
  // Lead 40
  {
    leadName: 'Vijay Malhotra',
    institution: 'Sanskriti School',
    phoneNumber: '9267890123',
    city: 'Delhi',
    priority: 'Low',
    stage: 'Future Connect',
    source: 'Referral',
    owner: 'Rahul Mehta',
    status: 'Connected',
    createdAt: '2025-08-30T09:55:00Z',
  },
  // Lead 41
  {
    leadName: 'Anand Rajan',
    institution: 'Padma Seshadri',
    phoneNumber: '9178901234',
    city: 'Chennai',
    priority: 'Medium',
    stage: 'Demo Booked',
    source: 'Email Campaign',
    owner: 'Sneha Kapoor',
    status: 'Demo Done',
    createdAt: '2025-12-05T11:40:00Z',
  },
  // Lead 42
  {
    leadName: 'Pallavi Joshi',
    institution: 'Mayo College',
    phoneNumber: '9089012345',
    city: 'Jaipur',
    priority: 'High',
    stage: 'Call Done',
    source: 'Social Media',
    owner: 'Karan Malhotra',
    status: 'Follow-up',
    createdAt: '2025-01-25T13:10:00Z',
  },
  // Lead 43
  {
    leadName: 'Ramesh Patil',
    institution: 'Scindia School',
    phoneNumber: '9890123456',
    city: 'Gwalior',
    priority: 'Low',
    stage: 'Followup Done',
    source: 'Website',
    owner: 'Deepika Iyer',
    status: 'FOLLOW_UP',
    createdAt: '2025-06-02T15:50:00Z',
  },
  // Lead 44
  {
    leadName: 'Swati Deshmukh',
    institution: 'Welham Girls',
    phoneNumber: '9701234567',
    city: 'Dehradun',
    priority: 'High',
    stage: 'Negotiation',
    source: 'Referral',
    owner: 'Ananya Sharma',
    status: 'Closed Won',
    createdAt: '2025-03-08T10:20:00Z',
  },
  // Lead 45
  {
    leadName: 'Karthik Subramanian',
    institution: 'Vidya Mandir',
    phoneNumber: '9612345670',
    city: 'Chennai',
    priority: 'Medium',
    stage: 'Demo Booked',
    source: 'Website',
    owner: 'Vikram Singh',
    status: 'Lost',
    createdAt: '2025-07-28T12:05:00Z',
  },
  // Lead 46
  {
    leadName: 'Preeti Chandra',
    institution: 'Doon School',
    phoneNumber: '9523456781',
    city: 'Dehradun',
    priority: 'High',
    stage: 'Followup Done',
    source: 'Referral',
    owner: 'Priya Patel',
    status: 'FOLLOW_UP',
    createdAt: '2025-09-15T14:35:00Z',
  },
  // Lead 47
  {
    leadName: 'Harsh Agarwal',
    institution: 'Birla School',
    phoneNumber: '9434567892',
    city: 'Jaipur',
    priority: 'Low',
    stage: 'Call Done',
    source: 'Email Campaign',
    owner: 'Rahul Mehta',
    status: 'Follow-up',
    createdAt: '2025-11-12T16:15:00Z',
  },
  // Lead 48
  {
    leadName: 'Madhuri Dixit',
    institution: 'Symbiosis School',
    phoneNumber: '9345678903',
    city: 'Pune',
    priority: 'Medium',
    stage: 'Future Connect',
    source: 'Social Media',
    owner: 'Sneha Kapoor',
    status: 'Connected',
    createdAt: '2025-05-08T09:25:00Z',
  },
  // Lead 49
  {
    leadName: 'Aditya Birla',
    institution: 'Mount Litera',
    phoneNumber: '9256789014',
    city: 'Mumbai',
    priority: 'High',
    stage: 'Demo Booked',
    source: 'Website',
    owner: 'Karan Malhotra',
    status: 'Demo Done',
    createdAt: '2025-10-05T11:50:00Z',
  },
  // Lead 50
  {
    leadName: 'Tanvi Sharma',
    institution: 'Tagore International',
    phoneNumber: '9167890125',
    city: 'Delhi',
    priority: 'Medium',
    stage: 'Negotiation',
    source: 'Referral',
    owner: 'Ananya Sharma',
    status: 'Closed Won',
    createdAt: '2025-12-12T13:00:00Z',
  },
];

// Call Logs seed data
const callLogsData = [
  {
    name: 'Gaurav Mishra',
    phoneNumber: '+91 99122 33445',
    callType: 'outgoing',
    duration: 536,
    simProvider: 'Vi',
    userEmail: 'admin@unite.com',
    callTime: new Date('2025-12-15T15:12:00Z'),
  },
  {
    name: 'Sumit Patel',
    phoneNumber: '+91 93456 78123',
    callType: 'unanswered',
    duration: 0,
    simProvider: 'Vi',
    userEmail: 'support@unite.com',
    callTime: new Date('2025-12-15T13:25:00Z'),
  },
  {
    name: 'Rakesh Kumar',
    phoneNumber: '+91 98012 23344',
    callType: 'unanswered',
    duration: 0,
    simProvider: 'Jio',
    userEmail: 'admin@unite.com',
    callTime: new Date('2025-12-15T11:59:00Z'),
  },
  {
    name: 'Gaurav Mishra',
    phoneNumber: '+91 99122 33445',
    callType: 'incoming',
    duration: 159,
    simProvider: 'Vi',
    userEmail: 'support@unite.com',
    callTime: new Date('2025-12-14T11:50:00Z'),
  },
  {
    name: 'Anita Rao',
    phoneNumber: '+91 99988 87776',
    callType: 'outgoing',
    duration: 222,
    simProvider: 'Airtel',
    userEmail: 'sales@unite.com',
    callTime: new Date('2025-12-13T20:34:00Z'),
  },
  {
    name: 'Divya Singh',
    phoneNumber: '+91 98114 56789',
    callType: 'missed',
    duration: 0,
    simProvider: 'Airtel',
    userEmail: 'admin@unite.com',
    callTime: new Date('2025-12-13T16:32:00Z'),
  },
  {
    name: 'Vikas Pandey',
    phoneNumber: '+91 98222 33446',
    callType: 'missed',
    duration: 0,
    simProvider: 'Jio',
    userEmail: 'sales@unite.com',
    callTime: new Date('2025-12-13T10:19:00Z'),
  },
  {
    name: 'Sumit Patel',
    phoneNumber: '+91 93456 78123',
    callType: 'incoming',
    duration: 365,
    simProvider: 'Vi',
    userEmail: 'support@unite.com',
    callTime: new Date('2025-12-12T16:50:00Z'),
  },
  {
    name: 'Simran Kaur',
    phoneNumber: '+91 98133 22110',
    callType: 'incoming',
    duration: 339,
    simProvider: 'Airtel',
    userEmail: 'support@unite.com',
    callTime: new Date('2025-12-12T15:10:00Z'),
  },
  {
    name: 'Anita Rao',
    phoneNumber: '+91 99988 87776',
    callType: 'incoming',
    duration: 515,
    simProvider: 'Airtel',
    userEmail: 'admin@unite.com',
    callTime: new Date('2025-12-12T13:50:00Z'),
  },
  {
    name: 'Sonal Gupta',
    phoneNumber: '+91 98123 45678',
    callType: 'outgoing',
    duration: 381,
    simProvider: 'BSNL',
    userEmail: 'support@unite.com',
    callTime: new Date('2025-12-12T11:15:00Z'),
  },
  {
    name: 'Lakshmi Nair',
    phoneNumber: '+91 98126 78901',
    callType: 'outgoing',
    duration: 582,
    simProvider: 'BSNL',
    userEmail: 'support@unite.com',
    callTime: new Date('2025-12-11T16:22:00Z'),
  },
  {
    name: 'Simran Kaur',
    phoneNumber: '+91 98133 22110',
    callType: 'unanswered',
    duration: 0,
    simProvider: 'Airtel',
    userEmail: 'sales@unite.com',
    callTime: new Date('2025-12-11T15:30:00Z'),
  },
  {
    name: 'Meena Agarwal',
    phoneNumber: '+91 98334 46655',
    callType: 'incoming',
    duration: 430,
    simProvider: 'BSNL',
    userEmail: 'support@unite.com',
    callTime: new Date('2025-12-10T09:43:00Z'),
  },
  {
    name: 'Surbhi Jain',
    phoneNumber: '+91 98887 76655',
    callType: 'incoming',
    duration: 69,
    simProvider: 'BSNL',
    userEmail: 'sales@unite.com',
    callTime: new Date('2025-12-09T13:30:00Z'),
  },
  {
    name: 'Shruti Desai',
    phoneNumber: '+91 99112 23344',
    callType: 'unanswered',
    duration: 0,
    simProvider: 'BSNL',
    userEmail: 'sales@unite.com',
    callTime: new Date('2025-12-08T19:43:00Z'),
  },
  {
    name: 'Vikas Pandey',
    phoneNumber: '+91 98222 33446',
    callType: 'outgoing',
    duration: 374,
    simProvider: 'Jio',
    userEmail: 'admin@unite.com',
    callTime: new Date('2025-12-08T18:29:00Z'),
  },
  {
    name: 'Sonal Gupta',
    phoneNumber: '+91 98123 45678',
    callType: 'outgoing',
    duration: 576,
    simProvider: 'BSNL',
    userEmail: 'sales@unite.com',
    callTime: new Date('2025-12-08T15:02:00Z'),
  },
  {
    name: 'Sonal Gupta',
    phoneNumber: '+91 98123 45678',
    callType: 'unanswered',
    duration: 0,
    simProvider: 'BSNL',
    userEmail: 'sales@unite.com',
    callTime: new Date('2025-12-07T11:11:00Z'),
  },
  {
    name: 'Manoj Kumar',
    phoneNumber: '+91 98001 12233',
    callType: 'outgoing',
    duration: 293,
    simProvider: 'Jio',
    userEmail: 'support@unite.com',
    callTime: new Date('2025-12-06T13:37:00Z'),
  },
  {
    name: 'Rahul Sharma',
    phoneNumber: '+91 98765 43210',
    callType: 'outgoing',
    duration: 67,
    simProvider: 'Jio',
    userEmail: 'support@unite.com',
    callTime: new Date('2025-12-06T12:39:00Z'),
  },
  {
    name: 'Meena Agarwal',
    phoneNumber: '+91 98334 46655',
    callType: 'unanswered',
    duration: 0,
    simProvider: 'BSNL',
    userEmail: 'sales@unite.com',
    callTime: new Date('2025-12-05T20:22:00Z'),
  },
  {
    name: 'Surbhi Jain',
    phoneNumber: '+91 98887 76655',
    callType: 'missed',
    duration: 0,
    simProvider: 'BSNL',
    userEmail: 'support@unite.com',
    callTime: new Date('2025-12-05T20:09:00Z'),
  },
  {
    name: 'Divya Singh',
    phoneNumber: '+91 98114 56789',
    callType: 'unanswered',
    duration: 0,
    simProvider: 'Airtel',
    userEmail: 'sales@unite.com',
    callTime: new Date('2025-12-05T13:20:00Z'),
  },
  {
    name: 'Anita Rao',
    phoneNumber: '+91 99988 87776',
    callType: 'missed',
    duration: 0,
    simProvider: 'Airtel',
    userEmail: 'support@unite.com',
    callTime: new Date('2025-12-05T11:30:00Z'),
  },
  {
    name: 'Simran Kaur',
    phoneNumber: '+91 98133 22110',
    callType: 'missed',
    duration: 0,
    simProvider: 'Airtel',
    userEmail: 'admin@unite.com',
    callTime: new Date('2025-12-04T16:10:00Z'),
  },
  {
    name: 'Surbhi Jain',
    phoneNumber: '+91 98887 76655',
    callType: 'outgoing',
    duration: 519,
    simProvider: 'BSNL',
    userEmail: 'sales@unite.com',
    callTime: new Date('2025-12-03T19:39:00Z'),
  },
  {
    name: 'Akash Mehta',
    phoneNumber: '+91 99223 34455',
    callType: 'outgoing',
    duration: 551,
    simProvider: 'Vi',
    userEmail: 'support@unite.com',
    callTime: new Date('2025-12-03T13:52:00Z'),
  },
  {
    name: 'Sonal Gupta',
    phoneNumber: '+91 98123 45678',
    callType: 'outgoing',
    duration: 330,
    simProvider: 'BSNL',
    userEmail: 'support@unite.com',
    callTime: new Date('2025-12-03T12:34:00Z'),
  },
  {
    name: 'Amit Sharma',
    phoneNumber: '+91 98701 23456',
    callType: 'outgoing',
    duration: 276,
    simProvider: 'Vi',
    userEmail: 'admin@unite.com',
    callTime: new Date('2025-12-02T11:13:00Z'),
  },
  {
    name: 'Priya Menon',
    phoneNumber: '+91 97654 32109',
    callType: 'missed',
    duration: 0,
    simProvider: 'Airtel',
    userEmail: 'support@unite.com',
    callTime: new Date('2025-12-02T11:03:00Z'),
  },
  {
    name: 'Surbhi Jain',
    phoneNumber: '+91 98887 76655',
    callType: 'incoming',
    duration: 57,
    simProvider: 'BSNL',
    userEmail: 'admin@unite.com',
    callTime: new Date('2025-12-01T19:05:00Z'),
  },
  {
    name: 'Anita Rao',
    phoneNumber: '+91 99988 87776',
    callType: 'outgoing',
    duration: 456,
    simProvider: 'Airtel',
    userEmail: 'support@unite.com',
    callTime: new Date('2025-12-01T17:25:00Z'),
  },
  {
    name: 'Vikas Pandey',
    phoneNumber: '+91 98222 33446',
    callType: 'unanswered',
    duration: 0,
    simProvider: 'Jio',
    userEmail: 'support@unite.com',
    callTime: new Date('2025-12-01T09:08:00Z'),
  },
  {
    name: 'Anita Rao',
    phoneNumber: '+91 99988 87776',
    callType: 'incoming',
    duration: 115,
    simProvider: 'Airtel',
    userEmail: 'admin@unite.com',
    callTime: new Date('2025-11-30T09:41:00Z'),
  },
  {
    name: 'Simran Kaur',
    phoneNumber: '+91 98133 22110',
    callType: 'incoming',
    duration: 413,
    simProvider: 'Airtel',
    userEmail: 'support@unite.com',
    callTime: new Date('2025-11-29T10:48:00Z'),
  },
  {
    name: 'Manoj Kumar',
    phoneNumber: '+91 98001 12233',
    callType: 'unanswered',
    duration: 0,
    simProvider: 'Jio',
    userEmail: 'support@unite.com',
    callTime: new Date('2025-11-28T10:36:00Z'),
  },
  {
    name: 'Lakshmi Nair',
    phoneNumber: '+91 98126 78901',
    callType: 'incoming',
    duration: 433,
    simProvider: 'BSNL',
    userEmail: 'support@unite.com',
    callTime: new Date('2025-11-28T09:08:00Z'),
  },
  {
    name: 'Shruti Desai',
    phoneNumber: '+91 99112 23344',
    callType: 'outgoing',
    duration: 273,
    simProvider: 'BSNL',
    userEmail: 'support@unite.com',
    callTime: new Date('2025-11-27T20:02:00Z'),
  },
  {
    name: 'Divya Singh',
    phoneNumber: '+91 98114 56789',
    callType: 'incoming',
    duration: 458,
    simProvider: 'Airtel',
    userEmail: 'admin@unite.com',
    callTime: new Date('2025-11-26T20:37:00Z'),
  },
  {
    name: 'Ravi Teja',
    phoneNumber: '+91 98767 12345',
    callType: 'missed',
    duration: 0,
    simProvider: 'Jio',
    userEmail: 'admin@unite.com',
    callTime: new Date('2025-11-26T17:49:00Z'),
  },
  {
    name: 'Divya Singh',
    phoneNumber: '+91 98114 56789',
    callType: 'unanswered',
    duration: 0,
    simProvider: 'Airtel',
    userEmail: 'admin@unite.com',
    callTime: new Date('2025-11-26T17:35:00Z'),
  },
  {
    name: 'Vikas Pandey',
    phoneNumber: '+91 98222 33446',
    callType: 'incoming',
    duration: 65,
    simProvider: 'Jio',
    userEmail: 'support@unite.com',
    callTime: new Date('2025-11-26T15:09:00Z'),
  },
  {
    name: 'Divya Singh',
    phoneNumber: '+91 98114 56789',
    callType: 'unanswered',
    duration: 0,
    simProvider: 'Airtel',
    userEmail: 'admin@unite.com',
    callTime: new Date('2025-11-25T18:05:00Z'),
  },
  {
    name: 'Lakshmi Nair',
    phoneNumber: '+91 98126 78901',
    callType: 'incoming',
    duration: 83,
    simProvider: 'BSNL',
    userEmail: 'sales@unite.com',
    callTime: new Date('2025-11-25T13:31:00Z'),
  },
  {
    name: 'Divya Singh',
    phoneNumber: '+91 98114 56789',
    callType: 'outgoing',
    duration: 384,
    simProvider: 'Airtel',
    userEmail: 'support@unite.com',
    callTime: new Date('2025-11-25T09:43:00Z'),
  },
  {
    name: 'Anita Rao',
    phoneNumber: '+91 99988 87776',
    callType: 'unanswered',
    duration: 0,
    simProvider: 'Airtel',
    userEmail: 'sales@unite.com',
    callTime: new Date('2025-11-24T19:12:00Z'),
  },
  {
    name: 'Sonal Gupta',
    phoneNumber: '+91 98123 45678',
    callType: 'missed',
    duration: 0,
    simProvider: 'BSNL',
    userEmail: 'support@unite.com',
    callTime: new Date('2025-11-22T12:14:00Z'),
  },
  {
    name: 'Surbhi Jain',
    phoneNumber: '+91 98887 76655',
    callType: 'unanswered',
    duration: 0,
    simProvider: 'BSNL',
    userEmail: 'support@unite.com',
    callTime: new Date('2025-11-22T09:32:00Z'),
  },
  {
    name: 'Akash Mehta',
    phoneNumber: '+91 99223 34455',
    callType: 'incoming',
    duration: 134,
    simProvider: 'Vi',
    userEmail: 'admin@unite.com',
    callTime: new Date('2025-11-21T20:02:00Z'),
  },
  {
    name: 'Shruti Desai',
    phoneNumber: '+91 99112 23344',
    callType: 'unanswered',
    duration: 0,
    simProvider: 'BSNL',
    userEmail: 'support@unite.com',
    callTime: new Date('2025-11-20T20:38:00Z'),
  },
  {
    name: 'Anita Rao',
    phoneNumber: '+91 99988 87776',
    callType: 'outgoing',
    duration: 215,
    simProvider: 'Airtel',
    userEmail: 'admin@unite.com',
    callTime: new Date('2025-11-20T20:26:00Z'),
  },
  {
    name: 'Sapna Joshi',
    phoneNumber: '+91 98776 65544',
    callType: 'unanswered',
    duration: 0,
    simProvider: 'Airtel',
    userEmail: 'admin@unite.com',
    callTime: new Date('2025-11-20T14:30:00Z'),
  },
  {
    name: 'Shruti Desai',
    phoneNumber: '+91 99112 23344',
    callType: 'missed',
    duration: 0,
    simProvider: 'BSNL',
    userEmail: 'admin@unite.com',
    callTime: new Date('2025-11-20T14:28:00Z'),
  },
  {
    name: 'Sumit Patel',
    phoneNumber: '+91 93456 78123',
    callType: 'incoming',
    duration: 168,
    simProvider: 'Vi',
    userEmail: 'admin@unite.com',
    callTime: new Date('2025-11-19T11:13:00Z'),
  },
  {
    name: 'Vikas Pandey',
    phoneNumber: '+91 98222 33446',
    callType: 'unanswered',
    duration: 0,
    simProvider: 'Jio',
    userEmail: 'support@unite.com',
    callTime: new Date('2025-11-19T10:09:00Z'),
  },
  {
    name: 'Shruti Desai',
    phoneNumber: '+91 99112 23344',
    callType: 'outgoing',
    duration: 550,
    simProvider: 'BSNL',
    userEmail: 'admin@unite.com',
    callTime: new Date('2025-11-18T10:49:00Z'),
  },
  {
    name: 'Vikas Pandey',
    phoneNumber: '+91 98222 33446',
    callType: 'unanswered',
    duration: 0,
    simProvider: 'Jio',
    userEmail: 'admin@unite.com',
    callTime: new Date('2025-11-17T16:06:00Z'),
  },
  {
    name: 'Vikas Pandey',
    phoneNumber: '+91 98222 33446',
    callType: 'incoming',
    duration: 106,
    simProvider: 'Jio',
    userEmail: 'admin@unite.com',
    callTime: new Date('2025-11-17T13:03:00Z'),
  },
  {
    name: 'Shruti Desai',
    phoneNumber: '+91 99112 23344',
    callType: 'outgoing',
    duration: 500,
    simProvider: 'BSNL',
    userEmail: 'sales@unite.com',
    callTime: new Date('2025-11-16T15:28:00Z'),
  },
  {
    name: 'Anita Rao',
    phoneNumber: '+91 99988 87776',
    callType: 'missed',
    duration: 0,
    simProvider: 'Airtel',
    userEmail: 'sales@unite.com',
    callTime: new Date('2025-11-14T19:25:00Z'),
  },
  {
    name: 'Rakesh Kumar',
    phoneNumber: '+91 98012 23344',
    callType: 'outgoing',
    duration: 233,
    simProvider: 'Jio',
    userEmail: 'support@unite.com',
    callTime: new Date('2025-11-14T14:17:00Z'),
  },
  {
    name: 'Divya Singh',
    phoneNumber: '+91 98114 56789',
    callType: 'missed',
    duration: 0,
    simProvider: 'Airtel',
    userEmail: 'admin@unite.com',
    callTime: new Date('2025-11-14T12:59:00Z'),
  },
  {
    name: 'Akash Mehta',
    phoneNumber: '+91 99223 34455',
    callType: 'unanswered',
    duration: 0,
    simProvider: 'Vi',
    userEmail: 'support@unite.com',
    callTime: new Date('2025-11-13T16:51:00Z'),
  },
  {
    name: 'Sonal Gupta',
    phoneNumber: '+91 98123 45678',
    callType: 'unanswered',
    duration: 0,
    simProvider: 'BSNL',
    userEmail: 'support@unite.com',
    callTime: new Date('2025-11-13T15:35:00Z'),
  },
  {
    name: 'Sapna Joshi',
    phoneNumber: '+91 98776 65544',
    callType: 'missed',
    duration: 0,
    simProvider: 'Airtel',
    userEmail: 'sales@unite.com',
    callTime: new Date('2025-11-13T10:55:00Z'),
  },
  {
    name: 'Lakshmi Nair',
    phoneNumber: '+91 98126 78901',
    callType: 'outgoing',
    duration: 557,
    simProvider: 'BSNL',
    userEmail: 'support@unite.com',
    callTime: new Date('2025-11-13T09:04:00Z'),
  },
  {
    name: 'Shruti Desai',
    phoneNumber: '+91 99112 23344',
    callType: 'incoming',
    duration: 168,
    simProvider: 'BSNL',
    userEmail: 'sales@unite.com',
    callTime: new Date('2025-11-12T18:42:00Z'),
  },
  {
    name: 'Anita Rao',
    phoneNumber: '+91 99988 87776',
    callType: 'unanswered',
    duration: 0,
    simProvider: 'Airtel',
    userEmail: 'support@unite.com',
    callTime: new Date('2025-11-11T20:12:00Z'),
  },
  {
    name: 'Gaurav Mishra',
    phoneNumber: '+91 99122 33445',
    callType: 'incoming',
    duration: 555,
    simProvider: 'Vi',
    userEmail: 'support@unite.com',
    callTime: new Date('2025-11-11T18:22:00Z'),
  },
  {
    name: 'Rakesh Kumar',
    phoneNumber: '+91 98012 23344',
    callType: 'outgoing',
    duration: 408,
    simProvider: 'Jio',
    userEmail: 'sales@unite.com',
    callTime: new Date('2025-11-11T16:30:00Z'),
  },
  {
    name: 'Anita Rao',
    phoneNumber: '+91 99988 87776',
    callType: 'outgoing',
    duration: 368,
    simProvider: 'Airtel',
    userEmail: 'sales@unite.com',
    callTime: new Date('2025-11-11T10:28:00Z'),
  },
  {
    name: 'Sonal Gupta',
    phoneNumber: '+91 98123 45678',
    callType: 'outgoing',
    duration: 471,
    simProvider: 'BSNL',
    userEmail: 'sales@unite.com',
    callTime: new Date('2025-11-10T19:00:00Z'),
  },
  {
    name: 'Priya Menon',
    phoneNumber: '+91 97654 32109',
    callType: 'incoming',
    duration: 144,
    simProvider: 'Airtel',
    userEmail: 'support@unite.com',
    callTime: new Date('2025-11-10T15:38:00Z'),
  },
  {
    name: 'Lakshmi Nair',
    phoneNumber: '+91 98126 78901',
    callType: 'unanswered',
    duration: 0,
    simProvider: 'BSNL',
    userEmail: 'support@unite.com',
    callTime: new Date('2025-11-10T12:08:00Z'),
  },
  {
    name: 'Sapna Joshi',
    phoneNumber: '+91 98776 65544',
    callType: 'missed',
    duration: 0,
    simProvider: 'Airtel',
    userEmail: 'sales@unite.com',
    callTime: new Date('2025-11-09T09:25:00Z'),
  },
  {
    name: 'Sumit Patel',
    phoneNumber: '+91 93456 78123',
    callType: 'outgoing',
    duration: 91,
    simProvider: 'Vi',
    userEmail: 'support@unite.com',
    callTime: new Date('2025-11-08T16:39:00Z'),
  },
  {
    name: 'Lakshmi Nair',
    phoneNumber: '+91 98126 78901',
    callType: 'outgoing',
    duration: 479,
    simProvider: 'BSNL',
    userEmail: 'sales@unite.com',
    callTime: new Date('2025-11-08T12:32:00Z'),
  },
  {
    name: 'Akash Mehta',
    phoneNumber: '+91 99223 34455',
    callType: 'missed',
    duration: 0,
    simProvider: 'Vi',
    userEmail: 'sales@unite.com',
    callTime: new Date('2025-11-08T11:17:00Z'),
  },
  {
    name: 'Anita Rao',
    phoneNumber: '+91 99988 87776',
    callType: 'outgoing',
    duration: 144,
    simProvider: 'Airtel',
    userEmail: 'sales@unite.com',
    callTime: new Date('2025-11-08T09:26:00Z'),
  },
  {
    name: 'Shruti Desai',
    phoneNumber: '+91 99112 23344',
    callType: 'unanswered',
    duration: 0,
    simProvider: 'BSNL',
    userEmail: 'support@unite.com',
    callTime: new Date('2025-11-07T20:41:00Z'),
  },
  {
    name: 'Simran Kaur',
    phoneNumber: '+91 98133 22110',
    callType: 'missed',
    duration: 0,
    simProvider: 'Airtel',
    userEmail: 'support@unite.com',
    callTime: new Date('2025-11-07T09:49:00Z'),
  },
  {
    name: 'Divya Singh',
    phoneNumber: '+91 98114 56789',
    callType: 'missed',
    duration: 0,
    simProvider: 'Airtel',
    userEmail: 'support@unite.com',
    callTime: new Date('2025-11-06T18:11:00Z'),
  },
  {
    name: 'Simran Kaur',
    phoneNumber: '+91 98133 22110',
    callType: 'unanswered',
    duration: 0,
    simProvider: 'Airtel',
    userEmail: 'sales@unite.com',
    callTime: new Date('2025-11-05T19:27:00Z'),
  },
  {
    name: 'Farhan Akhtar',
    phoneNumber: '+91 98445 56677',
    callType: 'incoming',
    duration: 166,
    simProvider: 'Vi',
    userEmail: 'sales@unite.com',
    callTime: new Date('2025-11-05T16:36:00Z'),
  },
  {
    name: 'Anita Rao',
    phoneNumber: '+91 99988 87776',
    callType: 'missed',
    duration: 0,
    simProvider: 'Airtel',
    userEmail: 'sales@unite.com',
    callTime: new Date('2025-11-05T09:23:00Z'),
  },
  {
    name: 'Manoj Kumar',
    phoneNumber: '+91 98001 12233',
    callType: 'incoming',
    duration: 581,
    simProvider: 'Jio',
    userEmail: 'sales@unite.com',
    callTime: new Date('2025-11-04T20:58:00Z'),
  },
  {
    name: 'Vikas Pandey',
    phoneNumber: '+91 98222 33446',
    callType: 'incoming',
    duration: 483,
    simProvider: 'Jio',
    userEmail: 'admin@unite.com',
    callTime: new Date('2025-11-04T18:39:00Z'),
  },
  {
    name: 'Akash Mehta',
    phoneNumber: '+91 99223 34455',
    callType: 'incoming',
    duration: 374,
    simProvider: 'Vi',
    userEmail: 'support@unite.com',
    callTime: new Date('2025-11-04T14:21:00Z'),
  },
  {
    name: 'Sonal Gupta',
    phoneNumber: '+91 98123 45678',
    callType: 'missed',
    duration: 0,
    simProvider: 'BSNL',
    userEmail: 'admin@unite.com',
    callTime: new Date('2025-11-03T09:57:00Z'),
  },
  {
    name: 'Lakshmi Nair',
    phoneNumber: '+91 98126 78901',
    callType: 'unanswered',
    duration: 0,
    simProvider: 'BSNL',
    userEmail: 'admin@unite.com',
    callTime: new Date('2025-11-02T12:32:00Z'),
  },
  {
    name: 'Lakshmi Nair',
    phoneNumber: '+91 98126 78901',
    callType: 'incoming',
    duration: 71,
    simProvider: 'BSNL',
    userEmail: 'admin@unite.com',
    callTime: new Date('2025-11-01T15:55:00Z'),
  },
  {
    name: 'Amit Sharma',
    phoneNumber: '+91 98701 23456',
    callType: 'unanswered',
    duration: 0,
    simProvider: 'Vi',
    userEmail: 'sales@unite.com',
    callTime: new Date('2025-11-01T13:50:00Z'),
  },
  {
    name: 'Gaurav Mishra',
    phoneNumber: '+91 99122 33445',
    callType: 'missed',
    duration: 0,
    simProvider: 'Vi',
    userEmail: 'support@unite.com',
    callTime: new Date('2025-11-01T13:03:00Z'),
  },
];

async function main() {
  console.log('🌱 Starting seed...');

  // Clear existing data
  console.log('🗑️ Clearing existing data...');
  await prisma.callLog.deleteMany({});
  await prisma.lead.deleteMany({});

  // Seed leads
  console.log('📋 Seeding leads...');
  for (const lead of leadsData) {
    await prisma.lead.create({
      data: {
        leadName: lead.leadName,
        institution: lead.institution,
        phoneNumber: lead.phoneNumber,
        city: lead.city,
        priority: mapPriority(lead.priority),
        stage: mapStage(lead.stage),
        source: mapSource(lead.source),
        owner: lead.owner,
        status: mapStatus(lead.status),
        createdAt: new Date(lead.createdAt),
      },
    });
  }
  console.log(`✅ Created ${leadsData.length} leads`);

  // Seed call logs
  console.log('📞 Seeding call logs...');
  for (const log of callLogsData) {
    await prisma.callLog.create({
      data: {
        name: log.name,
        phoneNumber: log.phoneNumber,
        callType: mapCallType(log.callType),
        duration: log.duration,
        simProvider: mapSimProvider(log.simProvider),
        userEmail: log.userEmail,
        callTime: log.callTime,
      },
    });
  }
  console.log(`✅ Created ${callLogsData.length} call logs`);

  console.log('🎉 Seed completed successfully!');
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
